=== aeremenok/a-team-777/trunk/10/pmhm/src/kurs/wireless/src/tech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/tech"
            xmlns:tns="http://xml.netbeans.org/schema/tech"
            elementFormDefault="qualified">
    <xsd:complexType name="person">
        <xsd:sequence>
            <xsd:element name="school" type="tns:school"/>
        </xsd:sequence>
        <xsd:attribute name="first_name" type="xsd:string" use="required"/>
        <xsd:attribute name="last_name" type="xsd:string"/>
        <xsd:attribute name="birth" type="xsd:date"/>
        <xsd:attribute name="place" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="school">
        <xsd:attribute name="number" type="xsd:int"/>
        <xsd:attribute name="description" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="article">
        <xsd:attribute name="title" type="xsd:string" use="required"/>
        <xsd:attribute name="created" type="xsd:date"/>
        <xsd:attribute name="author" type="xsd:string"/>
        <xsd:attribute name="content" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="impl">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="created" type="xsd:date"/>
        <xsd:attribute name="description" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="device">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="vendor" type="xsd:string" use="required"/>
        <xsd:attribute name="description" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="site">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="about">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="author" maxOccurs="unbounded" type="tns:person"/>
                        </xsd:sequence>
                        <xsd:attribute name="misc" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="articles">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="article" type="tns:article" maxOccurs="unbounded" minOccurs="0"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="standards">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="standard" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="impl" type="tns:impl"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="created" type="xsd:date"/>
                                    <xsd:attribute name="description" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="devices">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="device" type="tns:device" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== aeremenok/a-team-777/trunk/10/pmhm/src/kurs/wireless/src/site.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="articles.xsl"?>
<!--
    Document   : site.xml
    Created on : 25 Май 2008 г., 13:05
    Author     : eav
    Description:
        Это учебная работа по курсу ПСГМ.
-->
<site  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xsi:noNamespaceSchemaLocation="tech.xsd">
       
    <about>
        <author first_name="Андрей" last_name="Ерёменок" birth="1986-06-05" place="Ленинград">
            <school number="144">
                <description>
                    Гимназия Калининского района
                </description>
            </school>
            <university name="ЛЭТИ" accepted="2003-08-31" graduated="2009-02-18">
                <description>
                    Санкт-Петербургский Государственный Электротехнический Университет
                </description>
             </university>
        </author>
        <description>
            Это учебная работа по курсу ПСГМ.
        </description>
    </about>
    
    <articles>
        <article title="WiMAX: беспроводная магистраль в будущее" created="2005-11-15" author="Владимир Романченко">
            <content>
                Вначале был кабель. Нет, не так. В начале, конечно же, было слово, а затем дело, в результате чего появились компьютеры и другая электроника – от суперкластеров до мобильников. Затем появилась необходимость взаимодействия между всей этой электроникой. Так возник этот самый кабель, то есть, первые проводные интерфейсы. Затем, по мере развития технологий, и беспроводные. Оставляя за рамками этой заметки длительное и местами героическое прошлое проводных сетей, перейдем к самому интересному – ситуации нынешней и ближайшим беспроводным перспективам.
                Первыми робкими шагами по созданию беспроводных сетей стали возникновения отдельных точек доступа Wi-Fi с подключением к мощным магистральным "проводным" сетям, например, к оптоволоконным. В дальнейшем появился новый класс провайдеров, развернувших множественные коммерческие сети, в результате чего всего лишь за несколько лет сети Wi-Fi выросли в серьезные инфраструктуры - корпоративные и публичные. К настоящему моменту многие отели, аэропорты и вокзалы мира обладают покрытием Wi-Fi сетями, а в некоторых странах таким образом обеспечивается покрытие целых микрорайонов.
                ...
            </content>
        </article>
        
        <article title="Беспроводные сети. Стандарты" created="2003-01-20" author="Сергей Колесников">
            <content>
                Различных спецификаций стандартов беспроводных сетей семейства 802.1x существует великое множество (для обозначения одних только разновидностей стандарта 802.11 используются практически все буквы английского алфавита). Тем не менее, все они подразделяются на четыре большие категории WPAN, WLAN, WMAN, WWAN. Предлагаю рассмотреть каждую категорию подробнее.
                ...
            </content>
        </article>
        
        <article title="Технология Wireless USB" created="2007-12-12" author="Владимир Романченко">
            <content>
                Этой публикацией мы завершаем цикл статей, посвящённых долгому пути разработки, становления и прихода к массовому покупателю технологии Wireless USB. Относительно давно – по крайней мере, по сравнению со скоростями развития других компьютерных технологий, стандарт Wireless USB был представлен в качестве рабочего проекта; затем начали обновляться бета-версии его спецификаций, о чём подробно был изложено в наших публикациях, датированных ещё 2005 годом:
                ...
            </content>
        </article>
    </articles>
    
    <standards>
        <standard name="IEEE 802.15" created="2002-01-01">
            <impl name="Bluetooth IEEE 802.15.1" created="2002-01-01">
                <description>
                    Это стандарт передачи данных на малое расстояние (обычно десятки метров) и с низкой скоростью (до 2-3МБит/с на сегодня).
                </description>
            </impl>
            
            <impl name="ZigBee IEEE 802.15.4" created="2002-01-01">
                <description>
                    Это стандарт передачи данных на малые расстояния(10 до 75 м), с очень низкой скоростью (250 кбит/с), низкой стоимостью (1-3$/устройство) и низким энергопотреблением (нА в пассивном режиме) оборудования.
                </description>
            </impl>
            
            <description>
                WPAN
                Беспроводная сеть, предназначенная для организации беспроводной связи между различного типа устройствами на ограниченной площади (например, в рамках квартиры, офисного рабочего места).            
            </description>
        </standard>
        
        <standard name="IEEE 802.11 (Wi-Fi)" created="1997-01-01">
            <impl name="IEEE 802.11a" created="1997-01-01">
                <description>
                    Cтандарт беспроводных локальных сетей (WLAN), функционирующих в частотном диапазоне 5 ГГц (диапазон ISM). 
                    Беспроводные локальные сети стандарта IEEE 802.11a обеспечивают скорость передачи данных до 54 Мбит/с, что примерно в пять раз быстрее сетей стандарта IEEE 802.11b.
                </description>
            </impl>
            
            <impl name="IEEE 802.11n" created="2007-01-01">
                <description>
                    В основе - технология MIMO(Multiple Input, Multiple Output). Она повышает скорость передачи данных, используя феномен многолучевого распространения радиоволн. Он возникает, когда между ТД и клиентским устройством много разных путей передачи радиосигнала. Передавая по ним разные потоки данных (пространственное мультиплексирование), можно повысить эффективную пропускную способность соединения. Причем, чем больше потоков используется, тем она выше. Для передачи каждого потока нужно задействовать отдельную пару антенн, расположенных на обоих концах соединения.
                </description>
            </impl>
            
            <description>
                WLAN
                Беспроводная сеть соединяющая два и более устройства на коротком расстоянии – 30-150 метров, как в офисе так и дома. Wi-Fi – это доминирующий стандарт WLAN.
            </description>
        </standard>
        
        <standard name="IEEE 802.16" created="2001-01-01">
            <impl name="IEEE 802.16a" created="2001-01-01">
                <description>
                    Стационарный доступ
                </description>
            </impl>
            
            <impl name="IEEE 802.16e" created="2005-01-01">
                <description>
                    Мобильность
                </description>
            </impl>
            
            <description>
                Беспроводные сети масштаба города. Предоставляют широкополосный доступ к сети через радиоканал. Стандарт поддерживает топологию point-to-multipoint, технологии frequency-division duplex (FDD) и time-division duplex (TDD), с поддержкой quality of service (QoS). Возможна передача звука и видео.
            </description>
        </standard>
    </standards>
    
    <devices>
        <device name="" vendor="">
            <implements name="IEEE 802.16e">
                <description/>
            </implements>
            <description>sdfhjsh</description>
        </device>
        <device name="" vendor="">
            <implements name="IEEE 802.16e">
                <description/>
            </implements>
            <description>sdfasd</description>
        </device>
    </devices>
</site>
