=== aeremenok/a-team-777/trunk/10/GTM/epa/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- all common types -->
	<xs:simpleType name="mysimplestring" id="mysimplestring">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="telephone" id="telephone">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="myurl" id="myurl">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- used simple attribures -->
	<xs:element name="portalid" type="xs:nonNegativeInteger" />	
	<xs:element name="id" type="xs:nonNegativeInteger"/>
	<xs:element name="name" type="mysimplestring" nillable="false"/>
	<xs:element name="surname" type="mysimplestring"/>
	<xs:element name="birthdate" type="xs:date"/>
	<xs:element name="regdate" type="xs:date"/>
	<xs:element name="about" type="xs:string"/>
	
	<!-- CONTACTS -->
	<xs:element name="homephone" type="telephone"/>
	<xs:element name="cellphone" type="telephone"/>
	<xs:element name="icq" type="xs:int"/>
	<xs:element name="skype" type="mysimplestring"/>
	<xs:element name="email" type="mysimplestring"/>	
	<xs:element name="city" type="mysimplestring"/>
	<xs:element name="street" type="mysimplestring"/>
	<xs:element name="building" type="xs:int"/>
	<xs:element name="home" type="xs:int"/>
	<xs:element name="flat" type="xs:byte"/>
	<xs:element name="adress" nillable="false">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="city" minOccurs="0"/>
				<xs:element ref="street" minOccurs="0"/>
				<xs:element ref="home" minOccurs="0"/>
				<xs:element ref="building" minOccurs="0"/>
				<xs:element ref="flat" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="contacts" nillable="false">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cellphone" minOccurs="0"/>
				<xs:element ref="homephone" minOccurs="0"/>
				<xs:element ref="icq" minOccurs="0"/>
				<xs:element ref="skype" minOccurs="0"/>
				<xs:element ref="email" minOccurs="0"/>
				<xs:element ref="adress" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- HOBBIES -->
	<xs:element name="hobby" type="xs:string"/>
	<xs:element name="hobbies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hobby" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- FOTOS -->
	<xs:element name="foto">
		<xs:complexType>
			<xs:attribute name="path" type="myurl" use="required"/>
			<xs:attribute name="id" type="xs:byte" use="required"/>
			<xs:attribute name="comment" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="200"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- assembling all -->
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portalid"/>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="surname"/>
				<xs:element ref="birthdate"/>
				<xs:element ref="regdate"/>
				<xs:element ref="about"/>
				<xs:element ref="contacts" minOccurs="0"/>
				<xs:element ref="hobbies" minOccurs="0"/>
				<xs:element ref="fotos" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aeremenok/a-team-777/10/GTM/epa/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl.xsl"?>
<person  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<portalid>3</portalid>
	<id>1</id>
	<name>Pavel</name>
	<surname>Emman</surname>
	<birthdate>1985-12-15</birthdate>
	<regdate>2008-05-12</regdate>
	<about>about about about</about>
	<contacts>
		<cellphone>+79217938792</cellphone>
		<homephone>4477062</homephone>
		<icq>203676365</icq>
		<skype>pavelmmn</skype>
		<email>epa.spb@gmail.com</email>
		<adress>
			<city>SPb</city>
			<street>Harodnaya</street>
			<home>82</home>
			<building>2</building>
			<flat>71</flat>
		</adress>
	</contacts>
	<hobbies>
		<hobby>swimming</hobby>
		<hobby>Table tennis</hobby>
		<hobby>music</hobby>
	</hobbies>
	<fotos>
		<foto id="1" path="img\1.gif" comment="first picture"/>
		<foto id="1" path="img\2.gif" comment="second picture"/>
		<foto id="2" path="img\3.gif" comment="third picture"/>
		<foto id="1" path="img\4.gif" comment="forth picture"/>
		<foto id="2" path="img\5.gif" comment="fifth picture"/>
		<foto id="2" path="img\6.gif" comment="on more comment for picture"/>
		<foto id="2" path="img\1.gif" comment="comments picture"/>
		<foto id="2" path="img\2.gif" comment="comments picture"/>
		<foto id="2" path="img\3.gif" comment="comments picture"/>
		<foto id="2" path="img\4.gif" comment="comments picture"/>
		
	</fotos>
</person>
