=== aeremenok/a-team-777/trunk/9/psgm/ssv-course/src/news.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT news (new*)>
<!ELEMENT new (title, body)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT body (para*)>
<!ELEMENT para (#PCDATA)>

=== aeremenok/a-team-777/trunk/9/psgm/ssv-course/src/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE news SYSTEM "news.dtd">
<?xml-stylesheet type="text/xsl" href="news.xsl"?>
<news>
	<new>
		<title>Экзамен по ООТ</title>
		<body>
            <para>Сегодня Спицын выдал материалы по экзамену и рассказал о его проведении:</para>
            <para />
            <para>* консультация в 18.00 8 января на кафедре</para>
            <para>* экзамен в 10.00 9 января в ЦИТе</para>
            <para>* билет содержит 2 теоретических вопроса, 1 практический (либо программирование на компе, либо проектирование на бумажке)</para>
            <para>* при подготовке теории пользоваться ничем нельзя, но если нужно будет привести сложный пример - его можно будет освежить в памяти из книжки или конспекта</para>
            <para>* после ответа теории можно выйти на 10-15 мин, затем практика до конца</para>
            <para />
            <para>PS patterns и refactoring - материалы на самостоятельную проработку</para>
        </body>
	</new>
	<new>
		<title>НИРС</title>
		<body>
            <para>Надо предоставить Григорьеву:</para>
            <para />
            <para>* ФИО, степень и место работы руководителя, тему будущей диссертации + план на все 4 семестра, с подписью руководителя и пометкой, что план разработан и работа ведется, выполнено то и то за первый семестр</para>
            <para>* Отчет по НИРС (по той работе что проделана за семестр), отчет предоствляется в стандартной форме и должен быть подписан руководителем и поставлена оценка + отзыв руководителя о работе (страниц 10, по словам Григорьева)</para>
            <para>* Оценка за НИРС учитывается в дипломе и влияет на его цвет.</para>
            <para />
            <para>Руководитель должен быть не ниже к.т.н.</para>
            <para />
            <para>Всю информацию нужно предоставить до 21 декабря. Григорьев будет с 16.00 до 18.00.</para></body>
	</new>
	<new>
		<title>Курсовик по СТ</title>
		<body>
            <para>Для тех, кто не нашёл в себе сил явиться на сегодняшнюю утреннюю пару, расскажу о тайном знании, что нам поведал товарищ Кринкин. Существуют 2 варианта выполнения курсовой.</para>
            <para />
            <para>Вариант 1 "Халява"</para>
            <para />
            <para>Берётся 3-я лабораторная работа, по ней пишется аккуратный отчёт и сдаётся. Это зачитывается за курсовую, но никаких бонусов на экзамене не даёт. Формат отчёта:</para>
            <para />
            <para>* Постановка задачи: краткое описание выбранного протокола прикладного уровня из RFC</para>
            <para>* Проектирование программной реализации: описание решения</para>
            <para>* Описание реализации: модули, классы, полномочия</para>
            <para>* Фрагменты текста + тестовые примеры</para>
            <para />
            <para>Вариант 2 "Полный Пэ"</para>
            <para />
            <para>Проектирование небольшой дрессированной сервис-ориентированной системы. Разрешено объединяться в банды по 2-3 человека. Требуется:</para>
            <para />
            <para>* Сформулировать или спросить у самого Кринкина пример бизнес-процесса</para>
            <para>* Сделать описание процесса в формате DFD либо IDF</para>
            <para>* Сформировать интерфейсы сервисов в формате WSDL (программно)</para>
            <para>* Сформировать описание процессов в формате BPEL (программно)</para>
            <para>* Программная реализация спроектированной системы</para>
            <para />
            <para>В данном варианте за WSDL обещается "4", за BPEL "5" и плюс балл на экзамене. Программная реализация грозит смельчакам автоматом на экзамене. И да не померкнет Их Слава в веках.</para></body>
	</new>
    <new>
		<title>Лабы по ООТ: великий последний шанс</title>
		<body>
            <para>Последняя лаба по ООТ будет на кафедре в среду 26 декабря с 15:20 и до упора. По возможности захватите ноутбуки, т.к. из лаборатории нас рано или поздно выгонят.</para></body>
	</new>
    <new>
		<title>Новости с фронта</title>
		<body>
            <para>Получил еще сводку от хостеров - борьба за живучесть дата-центра продолжается:</para>
            <para />
            <para>Сегодня (17/12/2007), в сети, от которой питается здание, где компания провайдер арендует серверное помещение, вышла из строя электроподстанция. В процессе ремонта подстанции потребовалось несколько переподключений на дизель-генератор и источники бесперебойного питания, в результате чего источники бесперебойного питания были разряжены и при очередном переходе на резервное питание перебоя в работе серверов избежать не удалось.</para>
            <para />
            <para>При попытках переключения на резервную подстанцию, серверная обесточивалась еще несколько раз.</para>
            <para />
            <para>Нами было принято решение отключить все оборудование серверной, во избежание поломок оборудования и перевести работу серверной от дизель- генератора.</para>
            <para />
            <para>На данный момент все серверы включены. В настоящее время ведутся работы по установке трех дополнительных источников бесперебойного питания и работы по ремонту подстанции. Мы постараемся произвести данные работы без отключения электропитания.</para>
            <para />
            <para>Провайдер арендует помещения для дата-центра у третьих лиц. В стоимость аренды входит резервное обеспечение питания через дизель-генератор. Провайдер имеет собственные УПСы, но неоднократные использование УПСов в течение короткого времени привело к разрядке батарей.</para>
            <para />
            <para>Наша компания уже занимается поиском другого датацентра для увеличения стабильности работы серверов и недопущения таких ситуация вновь, т.к. мы прекрасно понимаем, чем оборачиваются простои в работе сайтов и почты для Вас.</para></body>
	</new>
</news>
