=== aeremenok/a-team-777/10/pmhm/src/kurs/wireless/src/tech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/tech"
            xmlns:tns="http://xml.netbeans.org/schema/tech"
            elementFormDefault="qualified">
    <xsd:complexType name="person">
        <xsd:sequence>
            <xsd:element name="school" type="tns:school"/>
            <xsd:element name="university" type="tns:university"/>
        </xsd:sequence>
        <xsd:attribute name="first_name" type="xsd:string" use="required"/>
        <xsd:attribute name="last_name" type="xsd:string"/>
        <xsd:attribute name="birth" type="xsd:date"/>
        <xsd:attribute name="place" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="school">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
    
    <xsd:complexType name="university">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="accepted" type="xsd:date"/>
        <xsd:attribute name="graduated" type="xsd:date"/>
    </xsd:complexType>
    
    <xsd:complexType name="article">
        <xsd:sequence>
            <xsd:element name="content" type="xsd:string"/>
        </xsd:sequence>        
        <xsd:attribute name="title" type="xsd:string" use="required"/>
        <xsd:attribute name="created" type="xsd:date"/>
        <xsd:attribute name="author" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="impl">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="created" type="xsd:date"/>
        <xsd:attribute name="speed" type="xsd:int"/>
    </xsd:complexType>
    
    <xsd:complexType name="device">
        <xsd:sequence>
            <xsd:element name="implements" type="tns:impl"/>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="vendor" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:element name="site">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="about">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="author" maxOccurs="unbounded" type="tns:person"/>
                            <xsd:element name="description" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="articles">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="article" type="tns:article" maxOccurs="unbounded" minOccurs="0"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="standards">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="standard" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="impl" type="tns:impl" maxOccurs="unbounded"/>
                                        <xsd:element name="description" type="xsd:string"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="created" type="xsd:date"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="devices">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="device" type="tns:device" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== aeremenok/a-team-777/10/pmhm/src/kurs/wireless/src/site.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : site.xml
    Created on : 25 Май 2008 г., 2:36
    Author     : eav
    Description:
        Purpose of the document follows.
-->

<ns1:site  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='http://xml.netbeans.org/schema/tech'
   xsi:schemaLocation='http://xml.netbeans.org/schema/tech tech.xsd'>
        <ns1:about misc="">
                <ns1:author first_name="" last_name="" birth="" place="">
                        <ns1:school number="" description=""></ns1:school>
                    </ns1:author>
                <ns1:author first_name="" last_name="" birth="" place="">
                        <ns1:school number="" description=""></ns1:school>
                    </ns1:author>
                <ns1:author first_name="" last_name="" birth="" place="">
                        <ns1:school number="" description=""></ns1:school>
                    </ns1:author>
            </ns1:about>
        <ns1:articles>
                <ns1:article title="" created="" author="" content=""></ns1:article>
                <ns1:article title="" created="" author="" content=""></ns1:article>
                <ns1:article title="" created="" author="" content=""></ns1:article>
            </ns1:articles>
        <ns1:standards>
                <ns1:standard name="" created="" description="">
                        <ns1:impl name="" created="" description=""></ns1:impl>
                    </ns1:standard>
                <ns1:standard name="" created="" description="">
                        <ns1:impl name="" created="" description=""></ns1:impl>
                    </ns1:standard>
                <ns1:standard name="" created="" description="">
                        <ns1:impl name="" created="" description=""></ns1:impl>
                    </ns1:standard>
            </ns1:standards>
        <ns1:devices>
                <ns1:device name="" vendor=""></ns1:device>
                <ns1:device name="" vendor=""></ns1:device>
                <ns1:device name="" vendor=""></ns1:device>
            </ns1:devices>

</ns1:site>
