=== aeremenok/a-team-777/trunk/10/pmhm/src/AutoBiography/WebContent/schema.dtd
<!ELEMENT autobiography (header, author, relatives, legal) >
<!ELEMENT header (#PCDATA)>
<!ELEMENT author (
    credentials,
    school*,
    highSchool*,
    address
    ) >
<!ELEMENT relatives (relative*) >

<!ELEMENT relative (credentials)>
<!ATTLIST relative 
    status CDATA #REQUIRED
>

<!ELEMENT school (#PCDATA) >
<!ATTLIST school
    startDate CDATA #REQUIRED
    endDate CDATA #REQUIRED
    number CDATA #REQUIRED
    city CDATA #REQUIRED
>
<!ELEMENT highSchool (#PCDATA) >
<!ATTLIST highSchool
    startDate CDATA #REQUIRED
    endDate CDATA #IMPLIED
    schoolName CDATA #REQUIRED
    profession CDATA #REQUIRED
>

<!ELEMENT credentials (#PCDATA) >
<!ATTLIST credentials 
    fullName CDATA #REQUIRED
    birthDate CDATA #REQUIRED
    birthPlace CDATA #REQUIRED
>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address 
    city CDATA #REQUIRED
    district CDATA #REQUIRED
    street CDATA #REQUIRED
    house CDATA #REQUIRED
    appartment CDATA #REQUIRED
>

<!ELEMENT legal (#PCDATA)>
<!ATTLIST legal
    abroad CDATA #FIXED "Ближайших родственников, проживающих за границей, не имею."  
    court CDATA #FIXED "Я и мои ближайшие родственники под судом и следствием не находились." 
>

=== aeremenok/a-team-777/trunk/10/pmhm/src/AutoBiography/WebContent/eav.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="eav.xslt"?>
<!DOCTYPE autobiography SYSTEM "schema.dtd" >
<autobiography>
    <header>Автобиография</header>
    <author>
        <credentials
            birthDate="06-05-1986"
            birthPlace="Ленинград"
            fullName="Ерёменок Андрей Вячеславович"
        />
        <school
            startDate="01-09-1993"
            endDate="31-06-2003"
            city="Санкт-Петербург"
            number="144"
        />
        <highSchool
            startDate="31-08-2003"
            profession="220400"
            schoolName="ЛЭТИ"
        />
        <address
            appartment="000"
            city="Санкт-Петербург"
            district="Калининский"
            house="00"
            street="Тимуровская"
        />
    </author>
    <relatives>
        <relative status="мать">
            <credentials
                birthDate="26-02-1965"
                birthPlace="Ленинград"
                fullName="Ерёменок Лариса Валентиновна"
            />
        </relative>
        <relative status="отец">
            <credentials
                birthDate="11-02-1962"
                birthPlace="Освея"
                fullName="Ерёменок Вячеслав Тимофеевич"
            />
        </relative>
    </relatives>
    <legal
        abroad="Ближайших родственников, проживающих за границей, не имею."
        court="Я и мои ближайшие родственники под судом и следствием не находились."
    />
</autobiography>
